//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appOfflineApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string id { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string departamento { get; set; }
        public System.DateTime altaLog { get; set; }
        public Nullable<System.DateTime> modiLog { get; set; }
    }
}
